#!/bin/bash

echo "Build hook running"
echo "Building $IMAGE_NAME"
docker build --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
	--build-arg VCS_REF="$(git rev-parse --short HEAD)" \
	-t "$IMAGE_NAME" .
